# Generated by Django 4.2.1 on 2023-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
