# Generated by Django 4.2.1 on 2023-05-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_business_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='url',
            new_name='website',
        ),
    ]
